name: ci

on:
    pull_request:
        types: [reopened, opened, synchronize, ready_for_review, closed]

env:
    CICD_ODOO_OPTIONS: ${{ github.workspace }}/.cicd/conf/odoo.json
    ODOO_CUSTOM_ADDONS_PATH: ${{ github.workspace }}
    PIPELINE_SCRIPTS_PATH: ${{ github.workspace }}/.cicd/scripts
    PIPELINE_UTILS_SCRIPT_PATH: ${{ github.workspace }}/.cicd/scripts/utils.sh
    ODOO_IMAGE_TAG: xmars/odoo16-cicd
    ODOO_WORKSPACE: ${{ github.workspace }}/.cicd/odoo
    CONFIG_FILE: ${{ github.workspace }}/.cicd/odoo/etc/odoo.conf
    SOURCE_REQUIREMENTS_FILE: ${{ github.workspace }}/requirements.txt
    DOCKER_REQUIREMENTS_FILE: ${{ github.workspace }}/.cicd/odoo/dockerfile/requirements.txt
    ODOO_DOCKER_COMPOSE_PATH: ${{ github.workspace }}/.cicd/odoo
    ODOO_TEST_DATABASE_NAME: testing_db
    LOG_FILE: /var/log/odoo/odoo.log
    LOG_FILE_OUTSIDE: ${{ github.workspace }}/.cicd/odoo/logs/odoo.log
    ODOO_TMP_BACKUP_FOLDER: ${{ github.workspace }}/.cicd/.tmp/server-backup

    TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
    PR_URL: ${{ github.event.pull_request.html_url }}

    SERVER_HOST: ${{ vars.SERVER_HOST }}
    SERVER_USER: ${{ vars.SERVER_USER }}
    SERVER_PORT: ${{ vars.SERVER_PORT }}
    SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
    SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}

    SERVER_DEPLOY_PATH: ${{ vars.SERVER_DEPLOY_PATH }}
    SERVER_ODOO_URL: ${{ vars.SERVER_ODOO_URL }}
    SERVER_ODOO_DB_NAME: ${{ vars.SERVER_ODOO_DB_NAME }}
    SERVER_ODOO_IMAGE_TAG: ${{ vars.SERVER_ODOO_IMAGE_TAG }}

jobs:
    # TODO: integrate with Sonarqube
    pylint-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Prepare data for containers
              run: |
                  docker compose version
                  docker version
